local input = require("main.input_handler")
local system_movement = require("main.system_movement")


function init(self)
	self.speed = 200
	self.url_player = "/player"
	msg.post(".", "acquire_input_focus")
end


function on_input(self, action_id, action)
	input.process_input(action_id, action)
	system_movement.compute_raw_movement(input.get_key_state_table())
end


function update(self, dt)
	system_movement.update(self, dt)
end
